name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.7'
          extended: true
      - name: Run shellcheck
        uses: azohra/shellcheck-action@v0.8.0
      - name: Run Hugo build test
        run: tests/hugo_build_test.sh
