name: ShellCheck

on:
  push:
    paths:
      - 'bin/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'bin/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck bin/*.sh
